return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "svelte",
        "yaml",
        "gdscript",
        "godot_resource",
        "gdshader",
        "ruby",
        "elixir",
        "yaml",
      },
    },
  },
}
